# Generated by Django 3.0.6 on 2020-07-24 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='idNotification',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
