# Generated by Django 3.0.6 on 2020-07-24 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0002_user_idnotification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='idNotification',
            field=models.CharField(default='nothing', max_length=200),
        ),
    ]
