# Generated by Django 3.0.6 on 2020-08-07 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0004_auto_20200807_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='blocage',
            field=models.CharField(choices=[('Bloqué', 'Bloqué'), ('Débloqué', 'Débloqué'), ('En cours de traitement', 'En cours de traitement')], default='Débloqué', max_length=30),
        ),
    ]
